webdriver {
  driver = chrome
  autodownload = true
  timeouts {
    implicitlywait = 10000
    fluentwait = 10000
  }
  capabilities {
    browserName = "chrome"
    acceptInsecureCerts = true
  }
  base.url = "http://localhost:3001"
}

serenity {
  project.name = "AUTO_FRONT_POM_FACTORY"
  take.screenshots = FOR_FAILURES
  report.encoding = "UTF-8"
  timeout = 10000
}

headless.mode = false